//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;

//namespace Oops_practice
//{
//    public class Exception_Example
//    {
//        static void Main(string[] args)
//        {
//            try
//            {
//                int[] myNumbers = { 1, 2, 3 };
//                Console.WriteLine(myNumbers[10]);
//            }
//            catch (Exception e)
//            {
//                Console.WriteLine("Something went wrong: " + e.Message);
//            }
//            finally
//            {
//                Console.WriteLine("The 'try catch' is finished.");
//            }
//        }
//    }
//}
